// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxjmdcmjjnuzbjziyuiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4am1kY21qam51emJqeml5dWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDUzNTMsImV4cCI6MjA2MTMyMTM1M30.yL2YOm-eCoOinfAPqoil288Ibp5saPh56PKeXZEuPnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);